{
 "title": "Application_Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Etat Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UpTime Application",
   "type": "stat",
   "description": "la durée en secondes pendant laquelle le processus surveillé a été exécuté depuis son démarrage.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{application=\"Monitoring-App\", instance=\"monitoring-app:8081\"})"
    }
   ]
  },
  {
   "title": "Start Time Prometheus",
   "type": "stat",
   "description": "Date et Heure de lancement de serveur spring",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{instance=\"prometheus:9090\", job=\"prometheus\"})*1000"
    }
   ]
  },
  {
   "title": "Number of open files",
   "type": "stat",
   "description": "Cette métrique mesure le nombre de fichiers ouverts par un processus.",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_files_open_files{application=\"Monitoring-App\", instance=\"monitoring-app:8081\"}"
    }
   ]
  },
  {
   "title": "Process Metrics Collect",
   "type": "stat",
   "description": "Cette métrique mesure le nombre processus de collecte de métriques",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Start Time  Application",
   "type": "stat",
   "description": "Date et Heure de lancement de serveur spring",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{application=\"Monitoring-App\", instance=\"monitoring-app:8081\"})*1000"
    }
   ]
  },
  {
   "title": "Start Time System",
   "type": "stat",
   "description": "Date et Heure de lancement de serveur spring",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{instance=\"node-exporter:9100\", job=\"node-exporter\"})*1000"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "stat",
   "description": "Le nombre total des logs dans le processus est surveillé",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"error\",application=\"Monitoring-App\",instance=\"monitoring-app:8081\"}[1m]"
    }
   ]
  },
  {
   "title": "Total Logs",
   "type": "stat",
   "description": "Cette métrique mesure le nombre processus de collecte de métriques",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logback_events_total{application=\"Monitoring-App\",instance=\"monitoring-app:8081\"})"
    }
   ]
  },
  { "title": "CPU USED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"High_CPU_Busy\"})"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "État occupé de tous les cœurs de processeur ensemble , ansi État occupé par l'application ",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total{mode!=\"idle\"}) / sum(node_cpu_seconds_total)*100"
    },
    {
     "expr": "system_cpu_usage{exported_application=\"Monitoring-App\"}* 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "l'utilisation du processeur de  processus metrics par rapport à l'application Monitoring",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"monitoring-app:8081\", application=\"Monitoring-App\"}",
     "legendFormat": "System Cpu Usage"
    },
    {
     "expr": "process_cpu_usage{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "Process Cpu Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "mesure de la quantité de travail que le système gère actuellement et est utilisé pour évaluer la demande sur les ressources du système.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "Load Average"
    },
    {
     "expr": "system_cpu_count{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "Cpu Count"
    }
   ]
  },
  { "title": "RAM USED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"High_RAM_Busy\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\", job=\"node-exporter\"} * 100) / node_memory_MemTotal_bytes{instance=\"node-exporter:9100\", job=\"node-exporter\"})",
     "legendFormat": "System Ram"
    },
    {
     "expr": "100 * (sum(jvm_memory_used_bytes{exported_application=\"Monitoring-App\"})/sum(jvm_memory_max_bytes{exported_application=\"Monitoring-App\"}))",
     "legendFormat": "Application Ram"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "description": "La quantité de mémoire utilisée",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "{{id}} ({{area}})"
    }
   ]
  },
  {
   "title": "Committed Memory",
   "type": "graph",
   "description": "jvm_memory_committed_bytes fait généralement référence à la quantité totale de mémoire qui a été allouée par la machine virtuelle Java (JVM) pour être utilisée par l'application en cours d'exécution.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "{{id}} ({{area}})"
    }
   ]
  },
  { "title": "JVM Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "JVM Threads live",
   "type": "graph",
   "description": "JVM Threads are the threads that are created and managed by the Java Virtual Machine (JVM) to execute Java code.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"spring-actuator\"}",
     "legendFormat": "JVM Threads live"
    }
   ]
  },
  {
   "title": "JVM Threads States",
   "type": "graph",
   "description": "Les threads JVM peuvent être dans différents états, comme défini par la spécification de la machine virtuelle Java",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"spring-actuator\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Threads peak",
   "type": "graph",
   "description": "Permet de surveiller l'utilisation des threads d'une application Java et pour s'assurer que l'application ne crée pas trop de threads, ce qui peut entraîner des problèmes de performances et d'autres problèmes.",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"spring-actuator\"}",
     "legendFormat": "Threads peak"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 26 },
   "options": {
    "content": "# Threads\n\nLes threads sont des unités autonomes \npermettant l'exécution simultanée \nde différents traitements d'un \nmême programme.    "
   }
  },
  { "title": "JVM Garbage Collection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Max Data Size",
   "type": "graph",
   "description": "Taille maximale de memoire allouée par le JVM",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_max_data_size_bytes{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "Max Data Size"
    }
   ]
  },
  {
   "title": "Live Data Size",
   "type": "graph",
   "description": "Taille de memoire allouée par le JVM a cette instant",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "Live Data Size"
    }
   ]
  },
  {
   "title": "Pause Count",
   "type": "graph",
   "description": "Donne des informations sur la durée du nettoyage de la mémoire.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_count{exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "Pause Count"
    }
   ]
  },
  {
   "title": "Allocation Rate",
   "type": "graph",
   "description": "Incrément pour une augmentation de la taille du pool de mémoire de la jeune génération après un GC à avant le suivant",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "Allocation Rate"
    }
   ]
  },
  { "title": "Logback Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "INFO logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logback_events_total{application=\"Monitoring-App\", instance=\"monitoring-app:8081\", level=\"info\"}",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logback_events_total{application=\"Monitoring-App\", instance=\"monitoring-app:8081\", level=\"error\"}",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logback_events_total{application=\"Monitoring-App\", instance=\"monitoring-app:8081\", level=\"warn\"}",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logback_events_total{application=\"Monitoring-App\", instance=\"monitoring-app:8081\", level=\"debug\"}",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logback_events_total{application=\"Monitoring-App\", instance=\"monitoring-app:8081\", level=\"trace\"}",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}