{
 "title": "Kafka Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{instance=\"kafka:9292\", job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Total Brokers",
   "type": "stat",
   "description": "Total Brokers existing",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nkafka_brokers{instance=\"kafka-exporter:9308\", job=\"kafka-exporter\", middleware_type=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_usage{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}[5m]) * 100)"
    }
   ]
  },
  { "title": "Topic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Preferred Leader Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_leader_is_preferred)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Leader Broker per Partition",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 6 },
   "targets": [
    { "expr": "kafka_topic_partition_leader" }
   ]
  },
  {
   "title": "Total Topic Partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kafka_topic_partitions)", "legendFormat": "Topic Partitions" }
   ]
  },
  {
   "title": "In Sync Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica)"
    }
   ]
  },
  { "title": "Kafka Statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage Kafka",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", instance=\"kafka-lag-exporter:9999\", job=\"kafka-lag-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Kafka",
   "type": "graph",
   "description": "La métrique \"kafka_topic_partitions\" dans Prometheus est une mesure qui fournit des informations sur les partitions des sujets Kafka.\nDans un cluster Kafka, un sujet est divisé en plusieurs partitions.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partitions{job=\"kafka-exporter\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Kafka Lag Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Consumer Group Lag",
   "type": "graph",
   "description": "élai maximal observé entre la production et la consommation des messages par un groupe de consommateurs dans Apache Kafka.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{job=\"kafka-exporter\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Max Lag Seconds",
   "type": "graph",
   "description": "élai maximal observé entre la production et la consommation des messages par un groupe de consommateurs dans Apache Kafka.",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_max_lag_seconds{ job=\"kafka-lag-exporter\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Consumer Offset",
   "type": "graph",
   "description": "Décalage de décalage maximum pour chaque groupe de consommateurs.",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "offsets" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_offset{ job=\"kafka-lag-exporter\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Monitoring-Message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
   "repeat": "consumer_group",
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "sum((kafka_consumergroup_group_offset * 0)\n+ on(namespace,cluster_name,topic,partition) group_left() kafka_partition_latest_offset)",
     "legendFormat": "Consumer group lag in time"
    },
    {
     "expr": "sum(kafka_consumergroup_group_offset)",
     "legendFormat": "Sum of group offsets"
    },
    {
     "expr": "sum((kafka_consumergroup_group_offset * 0)\n+ on(namespace,cluster_name,topic,partition) group_left() kafka_partition_latest_offset)",
     "legendFormat": "Sum of latest offsets"
    }
   ]
  },
  {
   "title": "group-Monitor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_lag_seconds) ",
     "legendFormat": "Consumer group lag in time"
    },
    {
     "expr": "sum(kafka_consumergroup_group_offset)",
     "legendFormat": "Sum of group offsets"
    },
    {
     "expr": "sum((kafka_consumergroup_group_offset * 0) + on(namespace,cluster_name,topic,partition) group_left() kafka_partition_latest_offset)",
     "legendFormat": "Sum of latest offsets"
    }
   ]
  },
  {
   "title": "json-group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_lag_seconds)",
     "legendFormat": "Consumer group lag in time"
    },
    {
     "expr": "sum(kafka_consumergroup_group_offset)",
     "legendFormat": "Sum of group offsets"
    },
    {
     "expr": "sum((kafka_consumergroup_group_offset* 0)+ on(namespace,cluster_name,topic,partition) group_left() kafka_partition_latest_offset)",
     "legendFormat": "Sum of latest offsets"
    }
   ]
  },
  { "title": "JVM Metrics Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Total Threads Started",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_started_total{instance=\"kafka-lag-exporter:9999\", job=\"kafka-lag-exporter\"}"
    }
   ]
  },
  {
   "title": "JVM Threads current",
   "type": "graph",
   "description": "JVM Threads are the threads that are created and managed by the Java Virtual Machine (JVM) to execute Java code.",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"kafka-lag-exporter:9999\", job=\"kafka-lag-exporter\"}",
     "legendFormat": "JVM Threads current"
    }
   ]
  },
  {
   "title": "JVM Threads States",
   "type": "graph",
   "description": "Les threads JVM peuvent être dans différents états, comme défini par la spécification de la machine virtuelle Java",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"kafka-lag-exporter\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "JVM Threads States",
   "type": "graph",
   "description": "Les threads JVM peuvent être dans différents états, comme défini par la spécification de la machine virtuelle Java",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", instance=\"kafka-lag-exporter:9999\", job=\"kafka-lag-exporter\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}