apiVersion: v1
kind: Service
metadata:
  name: alert-manager
  namespace: monitoring
  labels:
    app: alert-manager
spec:
  selector:
    app: alert-manager
  ports:
    - name: alert-manager
      port: 9093
      targetPort: 9093
  type: ClusterIP
