apiVersion: v1
kind: Service
metadata:
  name: monitoring-app
  namespace: monitoring
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: monitoring-app
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer