apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  selector:
    app: cadvisor-monitoring
  ports:
    - name: cadvisor
      port: 8080
      targetPort: 8080
  type: ClusterIP