apiVersion: v1
kind: Service
metadata:
  name: kafka-lag-exporter
  namespace: monitoring
spec:
  selector:
    app: kafka-lag-exporter
  ports:
    - name: http
      port: 9999
      targetPort: 9999
  type: ClusterIP