apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  labels:
    io.soda.service: kafka
  name: kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    io.soda.service: kafka
status:
  loadBalancer: {}