apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: monitoring.actia.com
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: http
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  name: http
          - path: /monitoring-app
            pathType: Prefix
            backend:
              service:
                name: monitoring-app
                port:
                  name: tcp
          - path: /monitoring-dashboard
            pathType: Prefix
            backend:
              service:
                name: monitoring-dashboard
                port:
                  name: tcp