apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
        - name: app
          image: homranimahdi/diagcloud-metriques:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_BOOTSTRAP_SERVER
              value: kafka:9092
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: group-Monitor
            - name: SPRING_KAFKA_TEMPLATE_DEFAULT_TOPIC
              value: monitoring-topics
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5433/keycloak
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: NODE_EXPORTER_PORT
              value: "9100"
          volumeMounts:
            - name: prometheus-volume
              mountPath: /prometheus
      volumes:
        - name: prometheus-volume
          emptyDir: {}
      restartPolicy: Always