apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.10.0
          ports:
            - containerPort: 9115
          volumeMounts:
            - name: config-volume
              mountPath: /etc/blackbox-exporter/
          command:
            - /bin/blackbox_exporter
            - --config.file=/etc/blackbox-exporter/config.yml
      volumes:
        - name: config-volume
          configMap:
            name: blackbox-config
            items:
              - key: config.yml
                path: config.yml
      restartPolicy: Always