apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmx-exporter
  namespace: monitoring
  labels:
    app: jmx-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmx-exporter
  template:
    metadata:
      labels:
        app: jmx-exporter
    spec:
      containers:
        - name: jmx-exporter
          image: sscaling/jmx-prometheus-exporter
          ports:
            - containerPort: 5556
          resources: {}
      restartPolicy: Always