apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: monitoring
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: bitnami/kafka-exporter
          ports:
            - containerPort: 9308
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: KAFKA_SERVERS
              value: kafka:9092
            - name: KAFKA_EXPORTER_KAFKA_VERSION
              value: "3.4.0"

