
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  labels:
    io.soda.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.soda.service: kafka
  strategy: {}
  template:
    metadata:
      labels:
        io.soda.service: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: wurstmeister/kafka
          name: kafka
          ports:
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
