apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:11.0.2
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: postgres
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: keycloak
            - name: DB_PASSWORD
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: keycloak
            - name: KEYCLOAK_IMPORT
              value: /tmp/realm-monitoring.json
            - name: JAVA_OPTS
              value: "-Dkeycloak.profile.feature.upload_scripts=enabled"
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/jboss/keycloak/standalone/data
            - name: postgres-config
              mountPath: /docker-entrypoint-init.d
            - name: keycloak-config
              mountPath: /tmp/realm-monitoring.json
              subPath: realm-monitoring.json
      volumes:
        - name: keycloak-data
          emptyDir: {}
        - name: postgres-config
          configMap:
            name: postgres-config
        - name: keycloak-config
          configMap:
            name: keycloak-config