{
 "title": "Request_statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=~\"http_errors|http_response_time | http_Valid_response_time\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"http_response_time\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"http_Valid_response_time\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"http_errors\"})"
    }
   ]
  },
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "UpTime",
   "type": "stat",
   "description": "la durée en secondes pendant laquelle le processus surveillé a été exécuté depuis son démarrage.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{job=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"monitoring\"}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Date et Heure de lancement de serveur spring",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{job=\"monitoring\"})*1000"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "stat",
   "description": "Le nombre total d'erreurs présentées dans le processus est surveillé",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"error\",job=\"monitoring\"}"
    }
   ]
  },
  { "title": "Global Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"http_response_time\"})"
    }
   ]
  },
  {
   "title": "HTTP Total Requests ",
   "type": "stat",
   "description": "Count of servlet requests",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"Monitoring-App\", instance=\"monitoring-app:8081\", status=~\"2..|4..|5..\", uri!~\"/actuator/prometheus\"})",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Time",
   "type": "graph",
   "description": "Timer of servlet requests",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{application=\"Monitoring-App\", instance=\"monitoring-app:8081\", status=~\"2..|4..|5..\", uri!~\"/actuator/prometheus\"}",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Sucess Time",
   "type": "graph",
   "description": "Timer of servlet requests",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{application=\"Monitoring-App\", instance=\"monitoring-app:8081\",status=~\"2..\",uri=~\"/vci/.+|/User/.+|/ProductsInstance/.+|/SupportSession/.+|/DepConfiguration/.+\"}",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"http_Valid_response_time\"})"
    }
   ]
  },
  {
   "title": "Monitoring Sucess Request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"Monitoring-App\",instance=\"monitoring-app:8081\",status=~\"2..\", uri=~\"/vci/.+|/User/.+|/ProductsInstance/.+|/SupportSession/.+|/DepConfiguration/.+\"})"
    }
   ]
  },
  {
   "title": "HTTP Requests Fail Time",
   "type": "graph",
   "description": "Timer of servlet requests",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{application=\"Monitoring-App\", instance=\"monitoring-app:8081\",outcome=\"CLIENT_ERROR\"}",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"http_errors\"})"
    }
   ]
  },
  {
   "title": "Monitoring Fail Request",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"Monitoring-App\",instance=\"monitoring-app:8081\",status=~\"4..|5..\", outcome=\"CLIENT_ERROR\"})"
    }
   ]
  },
  { "title": "Request Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "API Vci",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"monitoring\",method=~\".+\",status=~\"2.+\",uri=~\"/vci/.+\"}",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"monitoring\",method=~\".+\",status=~\"4..|5..\",uri=~\"/vci/.+\"}",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "API Products Instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"monitoring\",method=~\".+\",status=~\"2.+\",uri=~\"/ProductsInstance/.+\"}",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"monitoring\",method=~\".+\",status=~\"4..|5..\",uri=~\"/ProductsInstance/.+\"}",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "API Support Session",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"monitoring\",method=~\".+\",status=~\"2.+\",uri=~\"/SupportSession/.+\"}",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"monitoring\",method=~\".+\",status=~\"4..|5..\",uri=~\"/SupportSession/.+\"}",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "API Dep Configuration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"monitoring\",method=~\".+\",status=~\"2.+\",uri=~\"/DepConfiguration/.+\"}",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"monitoring\",method=~\".+\",status=~\"4..|5..\",uri=~\"/DepConfiguration/.+\"}",
     "legendFormat": "ERROR"
    }
   ]
  },
  { "title": "VCI Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "POST Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"POST\",status=~\"2..\",uri=~\"/User/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"POST\",status=~\"4..|5..\",uri=~\"/User/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "GET Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"GET\",status=~\"2..\",uri=~\"/vci/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"GET\",status=~\"4..|5..\",uri=~\"/vci/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "DELETE Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"DELETE\",status=~\"2..\",uri=~\"/vci/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"DELETE\",status=~\"4..|5..\",uri=~\"/vci/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "PATCH Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"PATCH\",status=~\"2..\",uri=~\"/vci/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"PATCH\",status=~\"4..|5..\",uri=~\"/vci/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  { "title": "Products Instance Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "POST Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"POST\",status=~\"2..\",uri=~\"/ProductsInstance/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"POST\",status=~\"4..|5..\",uri=~\"/ProductsInstance/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "GET Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"GET\",status=~\"2..\",uri=~\"/ProductsInstance/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"GET\",status=~\"4..|5..\",uri=~\"/ProductsInstance/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "DELETE Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"DELETE\",status=~\"2..\",uri=~\"/ProductsInstance/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"DELETE\",status=~\"4..|5..\",uri=~\"/ProductsInstance/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "PATCH Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"PATCH\",status=~\"2..\",uri=~\"/ProductsInstance/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"PATCH\",status=~\"4..|5..\",uri=~\"/ProductsInstance/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  { "title": "Support Session Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "POST Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"POST\",status=~\"2..\",uri=~\"/SupportSession/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"POST\",status=~\"4..|5..\",uri=~\"/SupportSession/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "GET Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"GET\",status=~\"2..\",uri=~\"/SupportSession/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"GET\",status=~\"4..|5..\",uri=~\"/SupportSession/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "DELETE Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"DELETE\",status=~\"2..\",uri=~\"/SupportSession/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"DELETE\",status=~\"4..|5..\",uri=~\"/SupportSession/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "PATCH Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"PATCH\",status=~\"2..\",uri=~\"/SupportSession/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"PATCH\",status=~\"4..|5..\",uri=~\"/SupportSession/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  { "title": "Dep Configuration Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "POST Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"POST\",status=~\"2..\",uri=~\"/DepConfiguration/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"POST\",status=~\"4..|5..\",uri=~\"/DepConfiguration/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "GET Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"GET\",status=~\"2..\",uri=~\"/DepConfiguration/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"GET\",status=~\"4..|5..\",uri=~\"/DepConfiguration/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "DELETE Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"DELETE\",status=~\"2..\",uri=~\"/DepConfiguration/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"DELETE\",status=~\"4..|5..\",uri=~\"/DepConfiguration/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "PATCH Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"PATCH\",status=~\"2..\",uri=~\"/DepConfiguration/.+\"})",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"monitoring\",method=\"PATCH\",status=~\"4..|5..\",uri=~\"/DepConfiguration/.+\"})",
     "legendFormat": "ERROR"
    }
   ]
  }
 ]
}