apiVersion: v1
kind: Service
metadata:
  name: monitoring-dashboard
  namespace: monitoring
spec:
  selector:
    app: monitoring-dashboard
  ports:
    - port: 4201
      targetPort: 4201
  type: LoadBalancer
