apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer-service
  namespace: monitoring
spec:
  selector:
    app: grafana-image-renderer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 28080
