version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  app:
    build: ..
    image: pfe-back:latest
    container_name: pfe-back
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - prometheus
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: prod
      SPRING_PROFILES_DEFAULT: prod
      #SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      #SPRING_DATASOURCE_USERNAME: postgres
      #SPRING_DATASOURCE_PASSWORD: mysecretpassword
    command:
      - "--spring.profiles.active=dev"
