apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-front
  template:
    metadata:
      labels:
        app: pfe-front
    spec:
      containers:
        - name: pfe-front
          image: homranimahdi/pfe-front
          ports:
            - containerPort: 80
