apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-front
  labels:
    app: pfe-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-front
  template:
    metadata:
      labels:
        app: pfe-front
    spec:
      containers:
        - name: pfe-front
          image: homranimahdi/pfe-front:lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
