{
 "title": "Application_Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Etat Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UpTime Application",
   "type": "stat",
   "description": "la durée en secondes pendant laquelle le processus surveillé a été exécuté depuis son démarrage.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{application=\"Monitoring-App\", instance=\"monitoring-app:8081\"})"
    }
   ]
  },
  {
   "title": "Start Time Prometheus",
   "type": "stat",
   "description": "Date et Heure de lancement de serveur spring",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{instance=\"prometheus:9090\", job=\"prometheus\"})*1000"
    }
   ]
  },
  {
   "title": "Number of open files",
   "type": "stat",
   "description": "Cette métrique mesure le nombre de fichiers ouverts par un processus.",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_files_open_files{application=\"Monitoring-App\", instance=\"monitoring-app:8081\"}"
    }
   ]
  },
  {
   "title": "Process Metrics Collect",
   "type": "stat",
   "description": "Cette métrique mesure le nombre processus de collecte de métriques",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Start Time  Application",
   "type": "stat",
   "description": "Date et Heure de lancement de serveur spring",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{application=\"Monitoring-App\", instance=\"monitoring-app:8081\"})*1000"
    }
   ]
  },
  {
   "title": "Start Time System",
   "type": "stat",
   "description": "Date et Heure de lancement de serveur spring",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{instance=\"node-exporter:9100\", job=\"node-exporter\"})*1000"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "stat",
   "description": "Le nombre total des logs dans le processus est surveillé",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"error\",application=\"Monitoring-App\",instance=\"monitoring-app:8081\"}[1m]"
    }
   ]
  },
  {
   "title": "Total Logs",
   "type": "stat",
   "description": "Cette métrique mesure le nombre processus de collecte de métriques",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logback_events_total{application=\"Monitoring-App\",instance=\"monitoring-app:8081\"})"
    }
   ]
  },
  { "title": "CPU USED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"High_CPU_Busy\"})"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "État occupé de tous les cœurs de processeur ensemble , ansi État occupé par l'application ",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[5m])))) * 100"
    },
    {
     "expr": "(sum by(instance)(irate(system_cpu_usage{instance=\"monitoring-app:8081\", application=\"Monitoring-App\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "l'utilisation du processeur de  processus metrics par rapport à l'application Monitoring",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"monitoring-app:8081\", application=\"Monitoring-App\"}",
     "legendFormat": "System Cpu Usage"
    },
    {
     "expr": "process_cpu_usage{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "Process Cpu Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "Permet de déterminer si le système est surchargé ou non",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "Load Average"
    },
    {
     "expr": "system_cpu_count{application=\"monitoring\", exported_application=\"Monitoring-App\", instance=\"monitoring-app:8081\", job=\"monitoring\"}",
     "legendFormat": "Cpu Count"
    }
   ]
  },
  { "title": "RAM USED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"High_CPU_Busy\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\", job=\"node\"} * 100) / node_memory_MemTotal_bytes{instance=\"node-exporter:9100\", job=\"node\"})"
    },
    { "expr": "sum(jvm_memory_used_bytes)" }
   ]
  }
 ]
}