apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:8.0.6
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SERVER_HTTP_PORT
              value: "3000"
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_SERVER_ROOT_URL
              value: /
            - name: GF_SMTP_ENABLED
              value: "true"
            - name: GF_SMTP_HOST
              value: "smtp.outlook.com:587"
            - name: GF_SMTP_USER
              value: "mahdi.homrani@outlook.com"
            - name: GF_SMTP_PASSWORD
              value: "M20562219"
            - name: GF_SMTP_FROM_ADDRESS
              value: "mahdi.homrani@outlook.com"
            - name: GF_SMTP_FROM_NAME
              value: "Grafana"
            - name: GF_SMTP_SKIP_VERIFY
              value: "true"
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: "true"
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "esprit"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_RENDERING_SERVER_URL
              value: "http://grafana-image-renderer:28081/render"
            - name: GF_RENDERING_CALLBACK_URL
              value: "http://grafana:3000/"
            - name: GF_LOG_FILTERS
              value: "rendering:debug"
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          emptyDir: {}
